### ISSUE TITLE
Wordpress Support?

### ISSUE THREAD

**Issue by drawingfrommemory** [lord/middleman-php#13]
I was just wondering if anyone got this working with wordpress.
Indexes aren't supported, and when I go to index.php I get this error:

     Warning: require(./wp-blog-header.php): failed to open stream: No such file or directory in - on line 17 Fatal error: require(): Failed opening required './wp-blog-header.php' in - on line 17

**Comment by lord** [comment]
I'm going to close this, because I think Wordpress support is a little...ambitious for this humble project. :blush: However, if you or anybody else finds any tips or fixes to make it work, please do let us know!
