### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mcavallo** [lord/middleman-php#14]
While doing some edits to the readme file I noticed the project doesn't have a license

**Comment by mcavallo** [comment]
@lord what license do you have in mind for the project?

**Comment by lord** [comment]
MIT or Apache probably? Don't really have a preference between the two.

**Comment by mcavallo** [comment]
MIT sounds great I can add it with my next set of changes if that's OK with you.

**Comment by lord** [comment]
:+1: definitely, thanks so much!
