### ISSUE TITLE
Share sessions between pages

### ISSUE THREAD

**Issue by mcavallo** [lord/middleman-php#16]
At the moment It's not possible to share a session between different pages which is completely understandable given how the PHP code is executed.

We came up with a way to address this while implementing a CSRF check today which is perfect to run the code in development. Which is setting the session ID for all PHP requests directly inside the middleware before anything gets executed and using the same session_id every time:

```
session_id("middleman")
```

I wanted to check with you if you are interested on having this feature as part of the extension as we wrote most of the code already.

**Comment by lord** [comment]
:+1: yea, definitely! Like everything in middleman-php, it sounds incredibly hacky :smile: so some nice documentation in the README along with the feature would be probably a decent idea, but yea!

**Comment by mcavallo** [comment]
hehe indeed :smile: Will tidy up what we have and prepare the documentation as well.

**Comment by lord** [comment]
Also, @mcavallo I've added you as a collaborator — feel free (although don't feel obligated whatsoever!) to merge PRs, close issues, and make changes, and LMK (email is in profile) if you need a release cut for RubyGems.

**Comment by mcavallo** [comment]
Awesome! Thank you, I will be more than happy to keep the contributions coming whenever I find the time :smile:

**Comment by jamonholmgren** [comment]
:+1:

**Comment by mcavallo** [comment]
Added hacky shared sessions in 140718250630adf7785787608b1ad93148d0e275. Gonna try It out with a few test cases and report back any issues. Closing this for now.
